"""Fix provider field on item

Revision ID: 43189c2ce33e
Revises: fae9302098b1
Create Date: 2018-06-11 00:28:08.237313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43189c2ce33e'
down_revision = 'fae9302098b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('provider_id', sa.String(), nullable=True))
    op.drop_constraint('items_provier_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['provider_id'], ['id'])
    op.drop_column('items', 'provier_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('provier_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_provier_id_fkey', 'items', 'users', ['provier_id'], ['id'])
    op.drop_column('items', 'provider_id')
    # ### end Alembic commands ###
